# Filename of the user's public key blob
user_key = "publicKey.blob"
# Dump the original keys into files?
grab_keys = false
# Enable IP address replacement
replace_address = true
# Enable auto key negotiation (requires `replace_address`)
auto_key_fetch = true
# Fix encryption not being properly setup on wine (only useful to classic)
classic_wine_fix = false

# You can have multiple of those...
[[addresses]]
old = "gs0100.westus2.cloudapp.azure.com"
new = "example.com"

# ...like this
[[addresses]]
old = "gs0200.westus2.cloudapp.azure.com"
new = "example.com"
