name: Test and build
on: push
jobs:
  test:
    runs-on: windows-2022
    steps:
    - name: Pull repo
      uses: actions/checkout@v4
    - name: Build detour
      if: ${{ success() }}
      run: cargo build --release
    - name: Build DLL injector
      if: ${{ success() }}
      run: |
        cd dllhijack
        cargo build --release
    - name: Move build artifacts
      if: ${{ success() }}
      run: |
        mkdir output
        move target/release/rsa_inject.dll output/
        move dllhijack/target/release/dllhijack.dll output/eos_gaming.dll
        move config.toml output/
    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: injector
        path: ./output
