name: Test and build
on: push
# env: 
#   RUSTFLAGS: "-Dwarnings"
jobs:
  test:
    runs-on: windows-2022
    steps:
    - name: Pull repo
      uses: actions/checkout@v4
    # - name: Check
    #   if: ${{ success() }}
    #   run: cargo check --all-targets --all-features
    # - name: Run clippy
    #   if: ${{ success() }}
    #   run: cargo clippy --all-targets --all-features
    - name: Build detour
      if: ${{ success() }}
      run: cargo build --release
    - name: Build DLL injector
      if: ${{ success() }}
      run: |
        cd dllhijack
        cargo build --release
    - name: Move build artifacts
      if: ${{ success() }}
      run: |
        mkdir output
        move target/release/injector.exe output/
        move target/release/rsa_inject.dll output/
        move dllhijack/target/release/dllhijack.dll output/ddraw.dll
        move config.toml output/
    - name: Pack build artifacts
      if: ${{ success() }}
      run: 7z a -mx9 injector.7z output/*
    - name: Upload artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: injector.7z
        path: ./injector.7z
